### ISSUE TITLE
Run the project

### ISSUE THREAD

**Issue by Selendri** [pjchavarria/Swift-Widget#2]
Hi, 

Thx for your project. :)
I had an issue when I tried to run your project, i received this message.

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an SQL store with a nil URL.' 

Regards

**Comment by pjchavarria** [comment]
It's working for me, make sure you have groups enabled in Swift-Widget target > Capabilities section

**Comment by Selendri** [comment]
It works ^^
Indeed, the issue was Swift-WidgetToday didn't have the core data model in Build Phases > Copy Bundle Sources. Thank you !
